- type: latheRecipe
  id: ShellKS23Flashbang
  result: ShellKS23Flashbang
  category: Ammo
  completetime: 1
  materials:
    Steel: 40
    Plastic: 40
    Glass: 20

- type: latheRecipe
  id: ShellKS23Smoke
  result: ShellKS23Smoke
  category: Ammo
  completetime: 1
  materials:
    Steel: 20
    Plastic: 30
    Glass: 20

- type: latheRecipe
  id: ShellKS23Beanbag
  result: ShellKS23Beanbag
  category: Ammo
  completetime: 1
  materials:
    Steel: 30
    Plastic: 20

- type: latheRecipe
  id: ShellKS23Base
  result: ShellKS23Base
  category: Ammo
  completetime: 1
  materials:
    Steel: 20
    Plastic: 10