- type: ghostRole
  id: SyndicateAgentSpySmugger
  name: ghost-role-information-syndicate-reinforcement-spy-name
  description: ghost-role-information-syndicate-reinforcement-spy-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentSpy
  iconPrototype: ClothingMaskGasVoiceChameleon
  whitelisted: true

- type: entity
  parent: MobHumanSyndicateAgent
  id: MobHumanSyndicateAgentSpySmugger
  name: syndicate spy
  components:
  - type: Loadout
    prototypes: [SyndicateReinforcementSpySmugger]
    roleLoadout: [ RoleSurvivalSyndicate ]
