name: Publish Mapping

concurrency:
  group: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    #Forge-setup .NET start
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x
      env:
        DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet
 
    - name: Set DOTNET_ROOT and PATH
      run: |
        echo "DOTNET_ROOT=${{ runner.temp }}/.dotnet" >> $GITHUB_ENV
        echo "${{ runner.temp }}/.dotnet" >> $GITHUB_PATH
 
    - name: Check .NET installation
      run: dotnet --info
       #Forge-setup .NET end

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request_mapping.py
      env:
        PUBLISH_MAPPING_TOKEN: ${{ secrets.PUBLISH_MAPPING_TOKEN }}
        FORK_ID_MAPPING: ${{ vars.FORK_ID_MAPPING }}
